[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]

# In Cargo.toml
[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"  # If you also have client.rs
path = "src/client.rs"